x-env-vars: &env-vars
  RAILS_ENV: ${RAILS_ENV}
  DATABASE_URL: ${DATABASE_URL}
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}

services:
  web:
    image: ghcr.io/agilefreaks/blue-bottle-api:latest
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - .:/app:cached
    environment:
      <<: *env-vars
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
