# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.4.1
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    ruby-dev \
    gcc \
    make \
    libpq-dev \
    libyaml-dev \
    vim \
    curl \
    gnupg \
    git \
    libvips \
    libyaml-dev \
    postgresql-client

# Set the working directory
WORKDIR /app

# Set development environment
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

RUN gem update --system && gem install bundler

# Install gems
COPY Gemfile ./
RUN bundle install

# Copy application code
COPY . .

# Ensure logs, tmp, and storage directories are writable
RUN mkdir -p tmp/pids tmp/cache tmp/sockets log storage && \
    chmod -R 777 tmp log storage

COPY bin/dev /usr/bin/dev
RUN chmod +x /usr/bin/dev

# Entrypoint prepares the database.
COPY bin/docker-entrypoint /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint
ENTRYPOINT ["docker-entrypoint"]

# Expose port 3000 to the host
EXPOSE 3000
